### ISSUE TITLE
Traces too close to Calibration points

### ISSUE THREAD

**Issue by CacikeOtoao** [prusa3d/Heatbed_MK52_magnetic#3]
As seen on mk-52 12volt beds the copper traces were too close to the calibration points causing the PINDA to not find the reference points and failing calibration, therefore retracing was needed. Please update files to reflect these changes to the community.

**Comment by zbrozek** [comment]
The third probe point in particular is prone to calibration failure. It's also the only probe point that's got a continuous copper ocean completely around it.

Here's the worst point:
![image](https://user-images.githubusercontent.com/4878259/43040170-bebd28fc-8cf1-11e8-8593-ae13f9e66d4e.png)

Here's the best point:
![image](https://user-images.githubusercontent.com/4878259/43040174-d5326340-8cf1-11e8-9828-07c2de4efbaa.png)

**Comment by gregsaun** [comment]
I have received the first version of MK2.5 heated bed and 3 points have been cut out :

1st bed point 1:
![1stbed_point1](https://user-images.githubusercontent.com/12335098/43046922-4ec71da2-8dd0-11e8-87c2-878f5b3c5c9b.jpg)

1st bed point 2:
![1stbed_point2](https://user-images.githubusercontent.com/12335098/43046927-639ace36-8dd0-11e8-8ef8-0165be073907.jpg)

1st bed point 3:
![1stbed_point3](https://user-images.githubusercontent.com/12335098/43046929-6a1561a4-8dd0-11e8-8e93-8936594928c4.jpg)

1st bed point 4:
![1stbed_point4](https://user-images.githubusercontent.com/12335098/43046934-6f95f6de-8dd0-11e8-98c8-77fac48a1339.jpg)


My first bed was twisted and could never have a good first layer across the bed. Prusa sent my a new one and this one does not have cuts :

2nd bed point 1:
![2nd_bed_point1](https://user-images.githubusercontent.com/12335098/43046941-92556042-8dd0-11e8-95b5-d00bd7be83b5.jpg)

2nd bed point 2:
![2nd_bed_point2](https://user-images.githubusercontent.com/12335098/43046945-9cd0018a-8dd0-11e8-9e6f-68e7f2b962e6.jpg)

2nd bed point 3:
![2nd_bed_point3](https://user-images.githubusercontent.com/12335098/43046949-a58dfc8c-8dd0-11e8-903b-dd69a97b82c4.jpg)

2nd bed point 4:
![2nd_bed_point4](https://user-images.githubusercontent.com/12335098/43046953-ac413f26-8dd0-11e8-9d60-f34cdfde16aa.jpg)

Does this mean some files are missing or not synchronized anymore?

**Comment by gregsaun** [comment]
This could explain these issues as well :

https://github.com/prusa3d/Prusa-Firmware/issues/895
https://github.com/prusa3d/Prusa-Firmware/issues/764
https://github.com/prusa3d/Prusa-Firmware/issues/616

**Comment by zbrozek** [comment]
I used a razor blade to create some clearance from the third probe point to the trace immediately to the right. Then calibration worked on the first try.
![image](https://user-images.githubusercontent.com/4878259/43047245-2e04dace-8d89-11e8-80f3-94efadcaabff.png)

**Comment by matthew-humphrey** [comment]
Good work troubleshooting this guys. Up-voting to hopefully draw a response from Prusa.

**Comment by ok1hra** [comment]
This problem was solved in firmware [MK2.5 (3.1.4-RC1)](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.1.4-RC1) and later also [MK3 and MK2.5 (3.2.0-RC1)](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.2.0-RC1).
Therefore was no need changed Heatbed layout.

**Comment by zbrozek** [comment]
I was completely unable to complete a calibration with my brand-new mk52 12v bed with firmwares 3.1.3, 3.1.4, 3.2.0, 3.3.0, and 3.3.1 until I cut away the small section to the right of the probe point.

I do not believe that *any* firmware solution is possible. It is possible to traverse X at the highest Z at which a perfectly-centered PINDA just triggers and not have the PINDA output go high until it's past the edge of the board.

**Comment by zbrozek** [comment]
Here's a log from firmware 3.3.1 failing XYZ calibration on a stock 12v mk52 bed. Notice the bad 2D scan of point three after a false trigger during the initial spiraling search. This problem is **not fixed.**

[fw_3.3.1_xyz.log](https://github.com/prusa3d/Heatbed_MK52_magnetic/files/2226058/fw_3.3.1_xyz.log)

**Comment by CacikeOtoao** [comment]
@ok1hra So a design flaw gets compensated for in Firmware and doesn't get an actual fix. They are surely flexing the OSHW licensing. So the bed designed as it is will be unusable outside of the Official Prusa Firmware.

**Comment by zbrozek** [comment]
I don't think there's any issue with following the license or the spirit of it. But I do think that the bug isn't closed because no hardware fix is in place, and the firmware fix doesn't actually work. This is a negative-margin design and a minor tweak can fix it.

**Comment by sirBlargh** [comment]
Did my upgrade 6 days ago. It also failed at point 3 so I Talked with support.  First they suggested that I should adjust PINDA but that did not help. They then asked me to verify that it was 100mm from the back of the Z-frame to the closest part of the back feet. I had 101mm and changing that to 100mm solved it for me.

**Comment by zbrozek** [comment]
Yeah, over chat I was told to make sure that the PINDA was landing precisely in the center of the silkscreen circle. It wasn't, but I adjusted until it was. No change on point three. After I did my modifications and checked the calibration, it looked like my positional error was <0.2 mm in both X and Y. I would hope that calibration is tolerant to such small errors.

So I bought three more probes of various kinds. Only one was able to differentiate the probe point from the surrounding traces. It was an Omron unit; I can dig up the exact part number if anyone is interested.

I debated between installing that probe permanently, but decided that I would rather stick with more-stock hardware. The internal temperature sensor on the PINDA swayed me. Though I don't know how consistent the Omron part is over temperature. I supposed I should find out.
